src/Entity/Guest.php
<?php

namespace App\Entity;

use App\Entity\Client\Client;
use DateTime;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity]
#[UniqueEntity(fields: ['email', 'client'], message: 'This address email already exist with this client', errorPath: 'email')]
class Guest
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    #[Groups(['read_user', 'read_session'])]
    private int $id;

    #[ORM\Column(type: 'string', nullable: true)]
    #[Groups(['read_user', 'read_session'])]
    private ?string $firstName = null;

    #[ORM\Column(type: 'string', nullable: true)]
    #[Groups(['read_user', 'read_session'])]
    private ?string $lastName = null;

    #[ORM\Column(type: 'string', length: 180)]
    #[Groups(['read_user', 'read_session'])]
    private string $email;

    #[ORM\Column(type: 'datetime')]
    #[Groups(['read_user', 'read_session'])]
    private DateTimeInterface $createdAt;

    #[ORM\Column(type: 'boolean', nullable: false)]
    #[Groups(['read_session'])]
    private bool $emailSent = false;

    #[ORM\Column(type: 'boolean', nullable: false)]
    #[Groups(['read_user', 'read_session'])]
    private bool $unsubscribe = false;

    #[ORM\Column(type: 'integer')]
    #[Groups(['read_user', 'read_session'])]
    private int $opened = 0;

    #[ORM\Column(type: 'integer')]
    #[Groups(['read_user', 'read_session'])]
    private int $clicked = 0;

    #[ORM\Column]
    #[Groups(['read_session'])]
    private string $token;

    #[ORM\Column(type: 'boolean', nullable: false)]
    #[Groups(['read_session'])]
    private bool $isBounce = false;

    #[ORM\ManyToOne(targetEntity: Client::class, inversedBy: 'guests')]
    #[Groups(['read_user'])]
    private Client $client;

    #[ORM\ManyToOne(targetEntity: WebinarConvocation::class, inversedBy: 'guests')]
    private WebinarConvocation $webinarConvocation;

    /**
     * @throws \Exception
     */
    public function __construct()
    {
        $this->createdAt = new DateTime();
        $this->token = \md5(\random_bytes(64));
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCreatedAt(): DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getClient(): Client
    {
        return $this->client;
    }

    public function setClient(Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function isEmailSent(): bool
    {
        return $this->emailSent;
    }

    public function setEmailSent(bool $emailSent): self
    {
        $this->emailSent = $emailSent;

        return $this;
    }

    public function isUnsubscribe(): bool
    {
        return $this->unsubscribe;
    }

    public function setUnsubscribe(bool $unsubscribe): self
    {
        $this->unsubscribe = $unsubscribe;

        return $this;
    }

    public function getWebinarConvocation(): WebinarConvocation
    {
        return $this->webinarConvocation;
    }

    public function setWebinarConvocation(WebinarConvocation $webinarConvocation): self
    {
        $this->webinarConvocation = $webinarConvocation;

        return $this;
    }

    public function getOpened(): int
    {
        return $this->opened;
    }

    public function setOpened(int $opened): self
    {
        $this->opened = $opened;

        return $this;
    }

    public function getClicked(): int
    {
        return $this->clicked;
    }

    public function setClicked(int $clicked): self
    {
        $this->clicked = $clicked;

        return $this;
    }

    public function getToken(): string
    {
        return $this->token;
    }

    public function setToken(string $token): self
    {
        $this->token = $token;

        return $this;
    }

    public function getFullName(): string
    {
        return "{$this->getLastName()} {$this->getFirstName()}";
    }

    public function isBounce(): bool
    {
        return $this->isBounce;
    }

    public function setIsBounce(bool $isBounce): self
    {
        $this->isBounce = $isBounce;

        return $this;
    }
}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use App\Model\ApiResponseTrait;
use App\Repository\BounceRepository;
use App\Repository\ProviderSessionRepository;
use App\Repository\WidgetNewsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

#[Route('/dashboard')]
#[IsGranted('ROLE_MANAGER')]
class DashboardController extends AbstractController
{
    use ApiResponseTrait;

    public function __construct(
        private LoggerInterface $logger,
        private EntityManagerInterface $entityManager,
        private TranslatorInterface $translator
    ) {
    }

    #[Route('/current-session', name: '_dashboard_index', options: ['expose' => true])]
    public function listIncoming(ProviderSessionRepository $sessionRepository, BounceRepository $bounceRepository, WidgetNewsRepository $widgetNewsRepository): Response
    {
        $client = $this->getUser()->getClient();
        $now = (new \DateTimeImmutable())->setTime(0, 0);
        $aMonthInterval = \DateInterval::createFromDateString('30 day');

        return $this->render('dashboard/index.html.twig', [
            'title' => 'Running and incoming sessions',
            'currentSession' => $sessionRepository->getCurrentSession($client, $now),
            'statistics' => $sessionRepository->getPeriodStatistics($client, $now),
            'currentStatistics' => $sessionRepository->getPeriodStatistics($client, $now, $now->add($aMonthInterval)),
            'pastStatistics' => $sessionRepository->getPeriodStatistics($client, $now->sub($aMonthInterval), $now),
            'countMailInError' => $bounceRepository->getMailInErrorForSessionInPeriod($client, $now, $now->add($aMonthInterval)),
            'widgetNews' => $widgetNewsRepository->findByLangs([$this->getUser()->getPreferredLang()], 5),
        ]);
    }
}

templates/dashboard/index.html.twig
{% extends 'main.html.twig' %}
{% set routeActive = '_dashboard_index' %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('dashboard-current-session') }}
    {{ encore_entry_link_tags('widget-news') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('dashboard-current-session') }}
    {{ encore_entry_script_tags('widget-news') }}
{% endblock %}

{% block main %}
    <header>
        <div class="wrapper-header d-flex align-items-start justify-content-between mb-5">
            <div class="wrapper-header__infos">
                <div class="wrapper-header__infos__title d-flex align-items-center mb-13">
                    <h1>{{ 'Hello %username%'|trans({'%username%': app.user.fullName}) }}</h1>
                </div>
                <div class="wrapper-header__infos__notifications d-flex align-items-center">
                    <div class="wrapper-header__infos__notifications__errors-mails d-flex align-items-center">
                        <img src="{{ asset('build/static/icons/error_email.svg') }}" class="me-2" />
                        <span>{{ '%count% mails in error'|trans({'%count%': countMailInError}) }}</span>
                        <img style="margin-left: 20px" src="{{ asset('build/static/icons/question.svg') }}" data-bs-placement="right" data-bs-toggle="tooltip" title="{{ "See the number of emails that have not reached their recipients for your today's and upcoming sessions in order to correct them and send their convocations as soon as possible"|trans }}">
                    </div>
                    <!--
                    <div class="wrapper-header__infos__notifications__errors-sessions d-flex align-items-center">
                        <img src="{{ asset('build/static/icons/error_session.svg') }}" class="me-2" />
                        <span>{{ '%count% errors onto your running and incoming session'|trans({'%count%': '12'}) }}</span>
                    </div>
                    -->
                </div>
            </div>
        </div>
    </header>

    <div class="col-md-12">
        {% include('flash_messages.html.twig') %}
    </div>

    <section id="wrapper-content-sessions" class="wrapper-content-sessions wrapper-content-dashboard-stats">
        <div class="row">
            <div class="col-lg-12 col-xl-8 mr-auto">
                <div class="wrapper-content-sessions__current">
                    <div class="wrapper-content-sessions__current__title d-flex align-items-center">
                        <h2 class="me-2">{{ 'Running and incoming sessions'|trans }}</h2>
                        <div class="wrapper-content-sessions__current__title__count d-flex align-items-center justify-content-center">
                            <span data-testselector="global_count_session">{{ currentSession|length }}</span>
                        </div>
                        <a href="{{ url('_session_create_from_wizard') }}" class="primary-btn wrapper-content-sessions__current__title__new">
                            <img src="{{ asset('build/static/icons/plus-white.svg') }}" class="me-2"> {{ 'New'|trans }}
                        </a>
                    </div>
                    <div class="data-list mt-4" id="current-session">
                        <current-session
                            :current-session="{{ currentSession | serialize('json', {'groups': 'read_session_list'})}}"
                            :user="{{ app.user | serialize('json', {'groups': 'read_user_session_list'}) }}">
                        </current-session>
                    </div>
                    <div class="wrapper-content-sessions__current__all d-flex justify-content-end mt-30">
                        <a href="{{ url('_session_viewer') }}" class="btn btn-primary" role="button">{{ 'Display all running and incoming sessions'|trans }}</a>
                    </div>
                </div>

                <hr class="mt-56 mb-60">

                <div class="wrapper-content-dashboard-stats__session wrapper-container">
                    <div class="wrapper-content-sessions__current__title d-flex align-items-center mb-20">
                        <h2 class="me-2">{{ 'Running and incoming sessions statistics'|trans }}</h2>
                    </div>
                    <div class="wrapper-content-dashboard-stats__session__content d-flex">
                        <div class="wrapper-content-dashboard-stats__session__content__count col my-2">
                            <div class="d-flex flex-column justify-content-center align-items-center">
                                <div class="wrapper-content-dashboard-stats__session__content__count__total reduced-centered">
                                    <h4>{{ 'Sessions'|trans }}</h4>
                                </div>
                                <div class="wrapper-content-dashboard-stats__session__content__count__round green d-flex align-items-center justify-content-center">
                                    <span data-testselector="count_session">{{ statistics.count_session }}</span>
                                </div>
                                <div class="wrapper-content-dashboard-stats__session__content__count__total reduced-centered d-flex align-items-center justify-content-center">
                                    <span data-testselector="tendancy_session">{{ calculateTendency(currentStatistics.count_session, pastStatistics.count_session) }}&nbsp;</span>
                                    <img src="{{ asset('build/static/icons/question.svg') }}" data-bs-placement="left" data-bs-toggle="tooltip" title="{{ 'This trend is calculated based on the next 30 days compared to the past 30 days'|trans }}">
                                </div>
                            </div>
                        </div>
                        <div class="wrapper-content-dashboard-stats__session__content__count col my-2">
                            <div class="d-flex flex-column justify-content-center align-items-center">
                                <div class="wrapper-content-dashboard-stats__session__content__count__total reduced-centered">
                                    <h4>{{ 'Participants'|trans }}</h4>
                                </div>
                                <div class="wrapper-content-dashboard-stats__session__content__count__round bg-teal d-flex align-items-center justify-content-center">
                                    <span data-testselector="count_participant">{{ statistics.count_participant ?? 0 }}</span>
                                </div>
                                <div class="wrapper-content-dashboard-stats__session__content__count__total reduced-centered d-flex align-items-center justify-content-center">
                                    <span data-testselector="tendancy_participant">{{ calculateTendency(currentStatistics.count_participant|default(0), pastStatistics.count_participant|default(0)) }}&nbsp;</span>
                                    <img src="{{ asset('build/static/icons/question.svg') }}" data-bs-placement="left" data-bs-toggle="tooltip" title="{{ 'This trend is calculated based on the next 30 days compared to the past 30 days'|trans }}">
                                </div>
                            </div>
                        </div>
                        <div class="wrapper-content-dashboard-stats__session__content__count col my-2">
                            <div class="d-flex flex-column justify-content-center align-items-center">
                                <div class="wrapper-content-dashboard-stats__session__content__count__total reduced-centered d-flex align-items-center justify-content-center">
                                    <h4>{{ 'Duration'|trans }}</h4>
                                    <img style="margin-left: 10px" src="{{ asset('build/static/icons/question.svg') }}" data-bs-placement="right" data-bs-toggle="tooltip" title="{{ 'Average session length calculated ...'|trans }}">
                                </div>
                                <div class="wrapper-content-dashboard-stats__session__content__count__round bg-teal d-flex align-items-center justify-content-center">
                                    <span data-testselector="average_duration">
                                        {% set duration = ( statistics.count_session == 0 ) ? 0 : (statistics.sum_duration / statistics.count_session) %}
                                        {{ duration|convertMinuteToReadable(app.user.client.defaultLang) }}
                                    </span>
                                </div>
                                <div class="wrapper-content-dashboard-stats__session__content__count__total reduced-centered d-flex align-items-center justify-content-center">
                                    <span data-testselector="total_duration">{{ 'Total duration :'|trans }} {{ statistics.sum_duration | default(0) |convertMinuteToReadable(app.user.client.defaultLang) }}</span>
                                    <img style="margin-left: 5px" src="{{ asset('build/static/icons/question.svg') }}" data-bs-placement="left" data-bs-toggle="tooltip" title="{{ "Cumulative duration of today's and upcoming sessions"|trans }}">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="wrapper-content-sessions__current__all d-flex justify-content-end mt-2">
                        <a href="{{ path('_statistics') }}" class="btn btn-primary" role="button">{{ 'View statistics' | trans }}</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 col-xl-3" id="widget-news">
                <widget-news
                    :widget-news="{{ widgetNews | serialize('json', {'groups': 'read_widget_news'})}}"
                    :is-admin="{{ is_granted('ROLE_ADMIN')?'true':'false' }}"
                >
                </widget-news>
            </div>
        </div>
    </section>
{% endblock %}